// <copyright file="WormholeCrypto.cs" company="CSUploader">
// Copyright (c) CSUploader. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;

namespace CSUploader.Upload.Pipeline.Hosters.Wormhole;

/// <summary>
/// The wormhole.app end-to-end crypto, ported from <c>webtorrent/wormhole-crypto</c> (Feross's library)
/// and verified byte-for-byte against known-answer vectors generated by running that library in Node,
/// plus the RFC 8188 §3 test vectors. Everything hangs off a 16-byte random <b>main key</b> (which lives
/// only in the share link's <c>#fragment</c>) and a 16-byte random <b>salt</b>:
/// <list type="bullet">
///   <item><b>readerToken</b> = HKDF-SHA256(ikm=mainKey, salt, info="authentication", 16) — sent to the
///   server so it can authorise downloads; the main key itself never leaves the client.</item>
///   <item><b>metadata key</b> = HKDF-SHA256(ikm=mainKey, salt, info="metadata", 16) — AES-128-GCM key
///   for the encrypted <c>.torrent</c> (<see cref="EncryptMeta"/>, 16-byte random IV prepended).</item>
///   <item><b>file content</b> = RFC 8188 "aes128gcm" Encrypted-Content-Encoding (<see cref="EceEncrypt"/>):
///   a 21-byte header (random salt ‖ rs ‖ idlen=0) then AES-128-GCM records of <c>rs</c> bytes whose CEK +
///   base nonce are HKDF-derived from the main key and the <em>header</em> salt (self-contained, so the
///   recipient reads it from the stream).</item>
/// </list>
/// All inputs that vary (the two HKDF salts, the ece header salt, the meta IV) are accepted explicitly so
/// the KAT tests can reproduce a reference output exactly; the parameterless helpers generate them randomly.
/// </summary>
internal static class WormholeCrypto
{
    public const int KeyLength = 16;   // 128-bit main key
    public const int SaltLength = 16;  // 128-bit salt
    public const int RecordSize = 65536; // ece "rs"
    public const int TagLength = 16;     // AES-GCM tag
    public const int HeaderLength = 21;  // salt(16) + rs(4) + idlen(1)

    // Plaintext bytes per ece record: rs minus the 16-byte tag and the 1-byte record delimiter.
    private const int RecordPlaintext = RecordSize - TagLength - 1; // 65519

    private static readonly byte[] InfoAuth = Encoding.ASCII.GetBytes("authentication");
    private static readonly byte[] InfoMeta = Encoding.ASCII.GetBytes("metadata");
    private static readonly byte[] InfoCek = Encoding.ASCII.GetBytes("Content-Encoding: aes128gcm\0");
    private static readonly byte[] InfoNonce = Encoding.ASCII.GetBytes("Content-Encoding: nonce\0");

    // ===== Random material =====
    public static byte[] RandomKey() => RandomNumberGenerator.GetBytes(KeyLength);

    public static byte[] RandomSalt() => RandomNumberGenerator.GetBytes(SaltLength);

    // ===== Encoders =====

    /// <summary>The main key as it appears in the share link's <c>#fragment</c>: base64url, no padding.</summary>
    public static string KeyToFragment(byte[] mainKey) => Base64Url(mainKey);

    /// <summary>Parses a main key out of a share-link fragment (base64url, padding-tolerant).</summary>
    public static byte[] KeyFromFragment(string fragment) => Base64UrlDecode(fragment);

    /// <summary>Standard base64 (with padding) — how the salt and tokens travel in the JSON bodies.</summary>
    public static string ToB64(byte[] bytes) => Convert.ToBase64String(bytes);

    // ===== Key derivations =====

    /// <summary>readerToken = HKDF-SHA256(mainKey, salt, "authentication", 16). Sent to the server.</summary>
    public static byte[] DeriveReaderToken(byte[] mainKey, byte[] salt)
        => HKDF.DeriveKey(HashAlgorithmName.SHA256, mainKey, KeyLength, salt, InfoAuth);

    /// <summary>metadata key = HKDF-SHA256(mainKey, salt, "metadata", 16). AES-128-GCM key for the .torrent.</summary>
    public static byte[] DeriveMetadataKey(byte[] mainKey, byte[] salt)
        => HKDF.DeriveKey(HashAlgorithmName.SHA256, mainKey, KeyLength, salt, InfoMeta);

    // ===== Size math (RFC 8188 framing overhead) =====

    /// <summary>Encrypted length of a plaintext of <paramref name="plaintextSize"/> bytes:
    /// 21-byte header + the data + 17 bytes (tag+delimiter) per record.</summary>
    public static long EncryptedSize(long plaintextSize)
        => HeaderLength + plaintextSize + (17L * RecordCount(plaintextSize));

    private static long RecordCount(long plaintextSize)
        => plaintextSize == 0 ? 0 : (plaintextSize + RecordPlaintext - 1) / RecordPlaintext;

    // ===== RFC 8188 content encryption =====

    /// <summary>Encrypts <paramref name="plaintext"/> as one RFC 8188 aes128gcm stream, generating a
    /// random header salt.</summary>
    public static byte[] EceEncrypt(ReadOnlySpan<byte> plaintext, byte[] mainKey)
        => EceEncrypt(plaintext, mainKey, RandomSalt());

    /// <summary>Encrypts <paramref name="plaintext"/> as one RFC 8188 aes128gcm stream using the given
    /// <paramref name="headerSalt"/> (written into the 21-byte header so the recipient can re-derive the
    /// keys). The CEK and base nonce are HKDF-SHA256(mainKey, headerSalt, …).</summary>
    public static byte[] EceEncrypt(ReadOnlySpan<byte> plaintext, byte[] mainKey, byte[] headerSalt)
        => EceEncryptCore(plaintext, mainKey, headerSalt, RecordSize, []);

    /// <summary>The generalised RFC 8188 record encoder. Production always uses
    /// <c>recordSize=65536, keyId=[]</c>; the extra parameters exist so the unit tests can reproduce the
    /// RFC 8188 §3.1/§3.2 vectors (which use a small <c>rs</c> and, in §3.2, a non-empty keyid).</summary>
    internal static byte[] EceEncryptCore(ReadOnlySpan<byte> plaintext, byte[] mainKey, byte[] headerSalt, int recordSize, byte[] keyId)
    {
        int recordPlaintext = recordSize - TagLength - 1;
        int headerLen = KeyLength + 4 + 1 + keyId.Length;
        long records = plaintext.Length == 0 ? 0 : (plaintext.Length + recordPlaintext - 1) / recordPlaintext;

        byte[] output = new byte[headerLen + plaintext.Length + (17L * records)];
        Span<byte> outSpan = output;

        // Header: salt(16) || rs(4, big-endian) || idlen(1) || keyid.
        headerSalt.CopyTo(outSpan);
        BinaryPrimitives.WriteUInt32BigEndian(outSpan.Slice(KeyLength, 4), (uint)recordSize);
        outSpan[KeyLength + 4] = (byte)keyId.Length;
        keyId.CopyTo(outSpan.Slice(KeyLength + 5));

        if (plaintext.Length == 0)
        {
            return output; // header only — matches wormhole-crypto for an empty input.
        }

        byte[] cek = HKDF.DeriveKey(HashAlgorithmName.SHA256, mainKey, KeyLength, headerSalt, InfoCek);
        byte[] baseNonce = HKDF.DeriveKey(HashAlgorithmName.SHA256, mainKey, 12, headerSalt, InfoNonce);

        using AesGcm aes = new(cek, TagLength);
        Span<byte> nonce = stackalloc byte[12];
        byte[] recordPlain = new byte[recordPlaintext + 1];

        int writePos = headerLen;
        for (long seq = 0; seq < records; seq++)
        {
            int dataOffset = (int)(seq * recordPlaintext);
            int dataLen = Math.Min(recordPlaintext, plaintext.Length - dataOffset);
            bool last = seq == records - 1;

            // Record plaintext = data || delimiter (0x01 non-final, 0x02 final). No extra padding.
            plaintext.Slice(dataOffset, dataLen).CopyTo(recordPlain);
            recordPlain[dataLen] = (byte)(last ? 2 : 1);
            Span<byte> recordPlainSpan = recordPlain.AsSpan(0, dataLen + 1);

            DeriveRecordNonce(baseNonce, seq, nonce);

            Span<byte> ct = outSpan.Slice(writePos, dataLen + 1);
            Span<byte> tag = outSpan.Slice(writePos + dataLen + 1, TagLength);
            aes.Encrypt(nonce, recordPlainSpan, ct, tag);
            writePos += dataLen + 1 + TagLength;
        }

        return output;
    }

    /// <summary>Per-record nonce = base nonce with its last 4 bytes XORed with the record sequence number
    /// (read/written big-endian), per RFC 8188 / wormhole-crypto's ece.js.</summary>
    private static void DeriveRecordNonce(byte[] baseNonce, long seq, Span<byte> nonce)
    {
        baseNonce.CopyTo(nonce);
        uint m = BinaryPrimitives.ReadUInt32BigEndian(nonce.Slice(8, 4));
        BinaryPrimitives.WriteUInt32BigEndian(nonce.Slice(8, 4), m ^ (uint)seq);
    }

    // ===== Metadata encryption (the encrypted .torrent) =====

    /// <summary>Encrypts metadata bytes with a random 16-byte IV.</summary>
    public static byte[] EncryptMeta(ReadOnlySpan<byte> meta, byte[] metadataKey)
        => EncryptMeta(meta, metadataKey, RandomNumberGenerator.GetBytes(16));

    /// <summary>Encrypts metadata as <c>IV(16) ‖ ciphertext ‖ tag(16)</c> with AES-128-GCM. wormhole-crypto
    /// uses a <b>16-byte</b> IV here (not the GCM-standard 12), which .NET's <see cref="AesGcm"/> rejects,
    /// so this path uses a self-contained GCM that accepts an arbitrary-length IV
    /// (<see cref="GcmEncryptAnyIv"/>).</summary>
    public static byte[] EncryptMeta(ReadOnlySpan<byte> meta, byte[] metadataKey, byte[] iv)
    {
        (byte[] ciphertext, byte[] tag) = GcmEncryptAnyIv(metadataKey, iv, meta);
        byte[] output = new byte[iv.Length + ciphertext.Length + tag.Length];
        iv.CopyTo(output, 0);
        ciphertext.CopyTo(output, iv.Length);
        tag.CopyTo(output, iv.Length + ciphertext.Length);
        return output;
    }

    // ===== AES-GCM with an arbitrary-length IV (NIST SP 800-38D), for the 16-byte meta IV =====

    /// <summary>AES-GCM encryption that accepts an IV of any length (the BCL's <see cref="AesGcm"/> only
    /// allows 12 bytes). Empty AAD. Returns (ciphertext, 16-byte tag). Verified against the wormhole-crypto
    /// <c>encryptMeta</c> KAT.</summary>
    internal static (byte[] Ciphertext, byte[] Tag) GcmEncryptAnyIv(byte[] key, byte[] iv, ReadOnlySpan<byte> plaintext)
    {
        using Aes aes = Aes.Create();
        aes.Mode = CipherMode.ECB;
        aes.Padding = PaddingMode.None;
        aes.Key = key;
        using ICryptoTransform ecb = aes.CreateEncryptor();

        byte[] EncryptBlock(byte[] block)
        {
            byte[] o = new byte[16];
            ecb.TransformBlock(block, 0, 16, o, 0);
            return o;
        }

        byte[] h = EncryptBlock(new byte[16]); // hash subkey H = AES_K(0^128)

        // J0: 96-bit IV -> IV||0x00000001; otherwise GHASH(IV padded || (0^64 || bitlen(IV))).
        byte[] j0;
        if (iv.Length == 12)
        {
            j0 = new byte[16];
            iv.CopyTo(j0);
            j0[15] = 1;
        }
        else
        {
            byte[] ghash = new byte[16];
            GhashUpdate(ghash, h, iv);
            byte[] lenBlock = new byte[16];
            BinaryPrimitives.WriteUInt64BigEndian(lenBlock.AsSpan(8), (ulong)iv.Length * 8);
            GhashBlock(ghash, h, lenBlock);
            j0 = ghash;
        }

        // CTR keystream starts at inc32(J0).
        byte[] ciphertext = new byte[plaintext.Length];
        byte[] counter = (byte[])j0.Clone();
        for (int offset = 0; offset < plaintext.Length; offset += 16)
        {
            Inc32(counter);
            byte[] ks = EncryptBlock(counter);
            int n = Math.Min(16, plaintext.Length - offset);
            for (int i = 0; i < n; i++)
            {
                ciphertext[offset + i] = (byte)(plaintext[offset + i] ^ ks[i]);
            }
        }

        // Tag = GHASH(C || lenblock(0 AAD bits, |C| bits)) XOR AES_K(J0).
        byte[] s = new byte[16];
        GhashUpdate(s, h, ciphertext);
        byte[] tagLen = new byte[16];
        BinaryPrimitives.WriteUInt64BigEndian(tagLen.AsSpan(0), 0); // AAD bit length = 0
        BinaryPrimitives.WriteUInt64BigEndian(tagLen.AsSpan(8), (ulong)ciphertext.Length * 8);
        GhashBlock(s, h, tagLen);
        byte[] ej0 = EncryptBlock(j0);
        byte[] tag = new byte[16];
        for (int i = 0; i < 16; i++)
        {
            tag[i] = (byte)(s[i] ^ ej0[i]);
        }

        return (ciphertext, tag);
    }

    /// <summary>Increment the rightmost 32 bits of a 16-byte counter block (big-endian), mod 2^32.</summary>
    private static void Inc32(byte[] counter)
    {
        uint c = BinaryPrimitives.ReadUInt32BigEndian(counter.AsSpan(12));
        BinaryPrimitives.WriteUInt32BigEndian(counter.AsSpan(12), c + 1);
    }

    /// <summary>GHASH over a byte stream: fold each 16-byte block (zero-padded) into <paramref name="y"/>.</summary>
    private static void GhashUpdate(byte[] y, byte[] h, ReadOnlySpan<byte> data)
    {
        Span<byte> block = stackalloc byte[16];
        for (int offset = 0; offset < data.Length; offset += 16)
        {
            block.Clear();
            int n = Math.Min(16, data.Length - offset);
            data.Slice(offset, n).CopyTo(block);
            for (int i = 0; i < 16; i++)
            {
                y[i] ^= block[i];
            }

            GfMul(y, h);
        }
    }

    /// <summary>GHASH a single (already 16-byte) block into <paramref name="y"/>.</summary>
    private static void GhashBlock(byte[] y, byte[] h, byte[] block)
    {
        for (int i = 0; i < 16; i++)
        {
            y[i] ^= block[i];
        }

        GfMul(y, h);
    }

    /// <summary>In-place GF(2^128) multiply <paramref name="x"/> *= <paramref name="h"/> (GCM's reducing
    /// polynomial, MSB-first bit order per NIST SP 800-38D).</summary>
    private static void GfMul(byte[] x, byte[] h)
    {
        Span<byte> z = stackalloc byte[16];
        Span<byte> v = stackalloc byte[16];
        h.CopyTo(v);

        for (int i = 0; i < 128; i++)
        {
            int bit = (x[i >> 3] >> (7 - (i & 7))) & 1;
            if (bit == 1)
            {
                for (int j = 0; j < 16; j++)
                {
                    z[j] ^= v[j];
                }
            }

            bool lsb = (v[15] & 1) != 0;
            for (int j = 15; j > 0; j--)
            {
                v[j] = (byte)((v[j] >> 1) | (v[j - 1] << 7));
            }

            v[0] >>= 1;
            if (lsb)
            {
                v[0] ^= 0xe1; // x^128 + x^7 + x^2 + x + 1 reduction
            }
        }

        z.CopyTo(x);
    }

    // ===== base64url helpers =====

    private static string Base64Url(byte[] data)
        => Convert.ToBase64String(data).TrimEnd('=').Replace('+', '-').Replace('/', '_');

    private static byte[] Base64UrlDecode(string s)
    {
        string b = s.Replace('-', '+').Replace('_', '/');
        return Convert.FromBase64String(b + new string('=', (4 - (b.Length % 4)) % 4));
    }
}
