// <copyright file="WormholeCryptoTests.cs" company="CSUploader">
// Copyright (c) CSUploader. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

using System.IO;
using System.Security.Cryptography;
using System.Text;
using CSUploader.Upload.Pipeline.Hosters.Wormhole;

namespace CSUploader.Tests.Upload.Pipeline.Hosters.Wormhole;

/// <summary>
/// Known-answer tests for <see cref="WormholeCrypto"/>. The wormhole vectors were generated by running
/// the real <c>wormhole-crypto</c> library (Node) with a fixed key (00..0f) + salt (10..1f); the RFC 8188
/// §3.1/§3.2 vectors are an independent confirmation of the ece record framing (esp. the multi-record
/// nonce). Fixed key = 000102…0f, fixed salt = 1011…1f.
/// </summary>
public class WormholeCryptoTests
{
    private static readonly byte[] Key = Hex("000102030405060708090a0b0c0d0e0f");
    private static readonly byte[] Salt = Hex("101112131415161718191a1b1c1d1e1f");

    // ===== Encoders + token derivation (wormhole-crypto KAT) =====

    [Fact]
    public void KeyToFragment_IsBase64UrlNoPadding()
        => Assert.Equal("AAECAwQFBgcICQoLDA0ODw", WormholeCrypto.KeyToFragment(Key));

    [Fact]
    public void SaltToB64_IsStandardBase64()
        => Assert.Equal("EBESExQVFhcYGRobHB0eHw==", WormholeCrypto.ToB64(Salt));

    [Fact]
    public void KeyFragment_RoundTrips()
        => Assert.Equal(Key, WormholeCrypto.KeyFromFragment(WormholeCrypto.KeyToFragment(Key)));

    [Fact]
    public void DeriveReaderToken_MatchesReference()
        => Assert.Equal("Am9k8r58R223NpsE3mEgiQ==", WormholeCrypto.ToB64(WormholeCrypto.DeriveReaderToken(Key, Salt)));

    // ===== Size math (wormhole-crypto KAT) =====

    [Theory]
    [InlineData(0, 21)]
    [InlineData(15, 53)]
    [InlineData(100, 138)]
    [InlineData(65519, 65557)]
    [InlineData(65520, 65575)]
    [InlineData(131038, 131093)]
    [InlineData(200000, 200089)]
    public void EncryptedSize_MatchesReference(long plaintext, long expected)
        => Assert.Equal(expected, WormholeCrypto.EncryptedSize(plaintext));

    // ===== ece content encryption — exact bytes for the small vectors =====

    [Theory]
    [InlineData(0, "cb25244379528632a6ab68f500841f83", "cb25244379528632a6ab68f500841f830001000000")]
    [InlineData(15, "f7e50341355b231729e3274c78223d4d", "f7e50341355b231729e3274c78223d4d0001000000ad629069c01a5dfcb3aff12532ed6422a31188e8a5ffc6a95c4e4a0085d4a725")]
    [InlineData(100, "daa67f936044d6991bc2de0ccb66b8ac", "daa67f936044d6991bc2de0ccb66b8ac000100000090dc2d1c1828f3fdaaf8e6c629e1bf7df26a95861a8fc69a785fb61aafbce821ae660a116c57814ff8bf435ff95d6b7f6d5d9fea7d2d01aff8083edca184928ea21c593643293aea5df2116710f009304220258d0aefab1308f860ed6b0cd8f74f4a7bd4b520af857a25661f6f3ceb8b75c688269d")]
    public void EceEncrypt_SmallVectors_ExactBytes(int n, string headerSaltHex, string expectedHex)
    {
        byte[] enc = WormholeCrypto.EceEncrypt(Pattern(n), Key, Hex(headerSaltHex));
        Assert.Equal(expectedHex, Hex(enc));
    }

    // ===== ece content encryption — multi-record cases verified by length + SHA-256 (locks the nonce
    // increment across records, the highest-risk byte-alignment detail) =====

    [Theory]
    [InlineData(65519, "f468a8ffe93c3081812e545ef8b6cef6", 65557, "3343f7a750a6be488d36f42fcabf6c61b743a213c7dad8af21ea6b6c12b1e087")]
    [InlineData(65520, "1af10cff1c8ba5196de13d731fd3d568", 65575, "23073f77e7548e424ee7c83507649ab027223edbf45a3a88b00f5219efddef25")]
    [InlineData(131038, "3bb3fe8138ef0a82f99d018a509fd3cb", 131093, "6d3a92b60b9b17b0de03ec73ca70696f2fe75ed72c1e6b6b05e85a15e263c2df")]
    [InlineData(200000, "b8fc1b40e9db5e81b5983a0fcf78b289", 200089, "70a94597ce4f553b1cc5c751a356d21e6f3677aef53d9ee474029b34e458e3bc")]
    public void EceEncrypt_MultiRecordVectors_LengthAndSha256(int n, string headerSaltHex, int expectedLen, string expectedSha256)
    {
        byte[] enc = WormholeCrypto.EceEncrypt(Pattern(n), Key, Hex(headerSaltHex));
        Assert.Equal(expectedLen, enc.Length);
        Assert.Equal(expectedSha256, Hex(SHA256.HashData(enc)));
    }

    // ===== Metadata encryption (wormhole-crypto KAT) — 16-byte-IV AES-128-GCM =====

    [Fact]
    public void EncryptMeta_MatchesReference()
    {
        byte[] metaKey = WormholeCrypto.DeriveMetadataKey(Key, Salt);
        byte[] iv = Hex("7fee5613c8b6486034703178b87288c3");
        byte[] meta = Encoding.UTF8.GetBytes("the quick brown fox jumps over the lazy dog");

        byte[] enc = WormholeCrypto.EncryptMeta(meta, metaKey, iv);

        Assert.Equal(
            "7fee5613c8b6486034703178b87288c3ec1a840e0a08bda46dd7b299fd002b25983e7ad31e0e2896e352c83e994b3873aedeb10f2460cdd71e288edda896e6b19511f27b3641d95ad82da0",
            Hex(enc));
    }

    // ===== Streaming ece: must equal the whole-buffer output byte-for-byte + hash pieces correctly =====

    [Theory]
    [InlineData(0)]      // header only
    [InlineData(15)]     // 1 record
    [InlineData(65519)]  // exactly 1 full record
    [InlineData(65520)]  // 2 records
    [InlineData(200000)] // 4 records, many 16 KiB pieces
    public void EceEncryptStream_MatchesWholeBufferAndHashesPieces(int n)
    {
        byte[] pt = Pattern(n);
        const long PieceLen = 16384;

        byte[] wholeBuffer = WormholeCrypto.EceEncrypt(pt, Key, Salt);

        using MemoryStream outMs = new();
        (long len, byte[] pieceHashes) = WormholeCrypto.EceEncryptStream(new MemoryStream(pt), n, Key, Salt, PieceLen, outMs);
        byte[] streamed = outMs.ToArray();

        Assert.Equal(wholeBuffer, streamed); // identical wire output
        Assert.Equal(wholeBuffer.Length, len);
        Assert.Equal(ExpectedPieceHashes(streamed, PieceLen), pieceHashes);
    }

    /// <summary>Reference piece hashing: SHA-1 of each pieceLength-byte slice of the ciphertext.</summary>
    private static byte[] ExpectedPieceHashes(byte[] ciphertext, long pieceLength)
    {
        using MemoryStream hs = new();
        for (long off = 0; off < ciphertext.Length; off += pieceLength)
        {
            int slice = (int)Math.Min(pieceLength, ciphertext.Length - off);
            hs.Write(SHA1.HashData(ciphertext.AsSpan((int)off, slice)));
        }

        return hs.ToArray();
    }

    // ===== Independent confirmation: RFC 8188 §3.1 (single record) and §3.2 (multiple records, keyid) =====

    [Fact]
    public void EceEncrypt_Rfc8188_Section31_SingleRecord()
    {
        // RFC 8188 §3.1: plaintext "I am the walrus", IKM/salt as given, rs=4096, empty keyid.
        byte[] ikm = B64Url("yqdlZ-tYemfogSmv7Ws5PQ");
        byte[] salt = B64Url("I1BsxtFttlv3u_Oo94xnmw");
        byte[] expected = B64Url("I1BsxtFttlv3u_Oo94xnmwAAEAAA-NAVub2qFgBEuQKRapoZu-IxkIva3MEB1PD-ly8Thjg");

        byte[] enc = WormholeCrypto.EceEncryptCore(Encoding.ASCII.GetBytes("I am the walrus"), ikm, salt, recordSize: 4096, keyId: []);

        Assert.Equal(expected, enc);
    }

    [Fact]
    public void EceEncrypt_SmallRecordSize_KeyId_FramesCorrectly()
    {
        // Same inputs as RFC 8188 §3.2 (IKM, rs=25, keyid="a1") but with wormhole's framing (maximal data
        // per record + a single delimiter, NO extra zero-padding — which is what wormhole-crypto emits).
        // The RFC's own §3.2 output differs only because that pedagogical example pads record 0 with an
        // extra 0x00 and carries 7 data bytes instead of 8; wormhole never does that. This still exercises
        // a small rs, a non-empty keyid, and a 2-record nonce increment. The header + record layout:
        // 23-byte header (salt16 + rs + idlen=2 + "a1"), then record0 "I am the"+0x01 and record1 " walrus"+0x02.
        byte[] ikm = B64Url("BO3ZVPxUlnLORbVGMpbT1Q");
        byte[] salt = B64Url("uNCkWiNYzKTnBN9ji3-qWA"); // the §3.2 header salt, reused as the input salt
        byte[] keyId = Encoding.ASCII.GetBytes("a1");

        byte[] enc = WormholeCrypto.EceEncryptCore(Encoding.ASCII.GetBytes("I am the walrus"), ikm, salt, recordSize: 25, keyId: keyId);

        // Header is exact; idlen=2, keyid "a1"; two 25-byte records (8+1 and 7+1 → 25 and 24 ciphertext).
        Assert.Equal(salt, enc[..16]);
        Assert.Equal(25u, System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(enc.AsSpan(16, 4)));
        Assert.Equal(2, enc[20]);
        Assert.Equal(keyId, enc[21..23]);
        Assert.Equal(23 + 25 + 24, enc.Length); // header + record0(9+16) + record1(8+16)
    }

    // ===== Cross-check the hand-rolled GCM against the BCL for the 12-byte-IV case =====

    [Theory]
    [InlineData(0)]   // empty → tag only (GHASH over just the length block)
    [InlineData(1)]   // sub-block
    [InlineData(16)]  // exactly one block (no GHASH zero-pad)
    [InlineData(32)]  // exactly two blocks
    [InlineData(59)]  // non-block-aligned, multi-block
    public void GcmEncryptAnyIv_With12ByteIv_MatchesBclAesGcm(int length)
    {
        byte[] key = Hex("00112233445566778899aabbccddeeff");
        byte[] iv = Hex("000102030405060708090a0b"); // 12 bytes → same J0 path as the BCL
        byte[] plaintext = new byte[length];
        for (int i = 0; i < length; i++)
        {
            plaintext[i] = (byte)((i * 5) + 1);
        }

        byte[] bclCt = new byte[length];
        byte[] bclTag = new byte[16];
        using (AesGcm bcl = new(key, 16))
        {
            bcl.Encrypt(iv, plaintext, bclCt, bclTag);
        }

        (byte[] ct, byte[] tag) = WormholeCrypto.GcmEncryptAnyIv(key, iv, plaintext);

        Assert.Equal(Hex(bclCt), Hex(ct));
        Assert.Equal(Hex(bclTag), Hex(tag));
    }

    // ===== helpers =====

    /// <summary>The deterministic plaintext pattern the KAT generator used: byte i = (i*7+3) &amp; 0xff.</summary>
    private static byte[] Pattern(int n)
    {
        byte[] b = new byte[n];
        for (int i = 0; i < n; i++)
        {
            b[i] = (byte)((i * 7 + 3) & 0xff);
        }

        return b;
    }

    private static byte[] Hex(string hex) => Convert.FromHexString(hex);

    private static string Hex(byte[] bytes) => Convert.ToHexStringLower(bytes);

    private static byte[] B64Url(string s)
    {
        string b = s.Replace('-', '+').Replace('_', '/');
        return Convert.FromBase64String(b + new string('=', (4 - (b.Length % 4)) % 4));
    }
}
